


apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-poc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
    
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deploy-svc
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30245
    
      
  selector:
    app: nginx
  type: NodePort
  # # externalTrafficPolicy: Local

  
  
 
  

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: default
  
spec:
  rules:
  - host: test.gotoadmins.cloud
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-deploy-svc
            port:
              number: 80
    
---


kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: default
data:
  proxy-protocol: "True"
  real-ip-header: "proxy_protocol"
  set-real-ip-from: "157.245.41.155"
  log_format:  '$remote_addr = $http_x_forwarded_for $remote_user [$time_local] "$request" ''$status $body_bytes_sent "$http_referer" ''"$http_user_agent" "$http_x_forwarded_for"'

